___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [2]:
# YOUR CODE IS HERE
import numpy as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [42]:
# YOUR CODE IS HERE
my_list = [5, 10, 15, 20, 25]
my_array = np.array(my_list)
my_array


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [49]:
# YOUR CODE IS HERE

my_zeros=np.zeros((5,5))
my_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [50]:
# YOUR CODE IS HERE
my_z=np.zeros((4,4), dtype= int)
my_z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 5. Make all the values of the array above with the value of 7.

In [15]:
# YOUR CODE IS HERE
my_z7=np.zeros((4,4), dtype= int)+7
my_z7


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [17]:
# YOUR CODE IS HERE
my_full=np.full((4, 4), 7)
my_full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [22]:
# YOUR CODE IS HERE

my_even=np.arange(2,17,2)
my_even

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [23]:
# YOUR CODE IS HERE

my_matrix=np.arange(0,25,1).reshape(5,5)
my_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [3]:
# YOUR CODE IS HERE

my_ls=np.linspace(0, 24, num=25, dtype= int).reshape(5,5)
my_ls

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [66]:
# YOUR CODE IS HERE

my_rndm=np.random.randn(5)
my_rndm

array([-0.15259548,  0.12119019, -0.26089082,  0.15895685,  0.47712242])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [14]:
# YOUR CODE IS HERE
my_rndm=np.random.randn(25).reshape(5,5)
my_rndm


array([[-0.24643441, -1.18686261,  0.53444344, -0.21330025,  0.94384263],
       [-0.01580413, -1.97550038,  1.24522663, -1.41420767, -0.49435073],
       [ 0.05256951, -0.58938979, -1.77291958, -0.02671706,  0.61486552],
       [-0.85267428,  1.55126907, -2.40137108,  0.54633736, -0.23028538],
       [-2.1457466 , -0.3792594 ,  0.72368145, -0.05911599, -1.17680501]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [51]:
# YOUR CODE IS HERE

my_rndm=np.random.randint(20,50,12).reshape(3,4)
my_rndm

array([[40, 37, 33, 23],
       [35, 30, 33, 39],
       [40, 47, 47, 38]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [67]:
# YOUR CODE IS HERE

ranarr=np.random.randint(1,100,48)
ranarr

array([47, 95,  4, 72, 65, 89, 16, 70, 12, 81, 75, 71, 90, 23, 25, 32, 39,
       45, 90, 30, 20, 84, 43, 25, 47,  1, 60, 87, 79, 64,  9, 11, 39, 80,
       10, 47, 17, 28,  1, 11, 97, 50, 76,  7, 60, 68, 82, 98])

In [68]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr.reshape(6,8)

array([[47, 95,  4, 72, 65, 89, 16, 70],
       [12, 81, 75, 71, 90, 23, 25, 32],
       [39, 45, 90, 30, 20, 84, 43, 25],
       [47,  1, 60, 87, 79, 64,  9, 11],
       [39, 80, 10, 47, 17, 28,  1, 11],
       [97, 50, 76,  7, 60, 68, 82, 98]])

In [52]:
# YOUR CODE IS HERE (RESHAPING WITH -1)


In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)



## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [16]:
# YOUR CODE IS HERE 
mat=np.arange(1,17,1).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [17]:
# YOUR CODE IS HERE 
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [18]:
# YOUR CODE IS HERE 
mat[:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [22]:
# YOUR CODE IS HERE 
mat[1,[0,2]]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [23]:
# YOUR CODE IS HERE 
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [24]:
# YOUR CODE IS HERE 
mat[[1,1],[0,2]]

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [32]:
# YOUR CODE IS HERE 


TypeError: ignored

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [35]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [36]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 
mat[mat<10]


array([1, 2, 4, 5, 6, 8, 9])

In [37]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
mat[mat>12]


array([77, 77, 77, 13, 14, 77, 16])

In [42]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
mat[mat<10]+mat[mat>12]


array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [50]:
# YOUR CODE IS HERE 
mat2=mat[mat<10]+mat[mat>12]
mat2.std()


29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [52]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [54]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat=np.arange(1,17,1).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
# YOUR CODE IS HERE 

mat[:,1].sum()

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [57]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

varr=mat[:,2]
varr

array([ 3,  7, 11, 15])

In [67]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 
varc=mat[2,:]
varc


array([ 9, 10, 11, 12])

In [73]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 
np.median(varr)

np.median(varc)

10.5

In [75]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

np.mean(varr)

np.mean(varc)

10.5

In [77]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 

varr.std()
varc.std()

1.118033988749895

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [103]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [104]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 
df=pd.read_csv("Salaries.csv")
df


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [105]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 

df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [106]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 

df.sample()

Id EmployeeName    JobTitle   BasePay  OvertimePay  OtherPay  \
49935  49936   Darby Reid  Sergeant 3  61884.04          0.0  41821.99   

       Benefits   TotalPay  TotalPayBenefits  Year  Notes         Agency  \
49935  15768.64  103706.03         119474.67  2012    NaN  San Francisco   

       Status  
49935     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [100]:
# YOUR CODE IS HERE 

type(df)

pandas.core.frame.DataFrame

In [107]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 
df.describe()


Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [109]:
# YOUR CODE IS HERE 

df.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [118]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
df.Year.nunique()


4

In [110]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
df.Year.unique()


array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [120]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 
df.TotalPay.max()


567595.43

In [122]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 
df.TotalPay.mean()


74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [124]:
# YOUR CODE IS HERE 


df.loc[df["TotalPay"]> df.TotalPay.mean()]


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 



### How much does ALBERT PARDINI make money (including benefits)?

In [127]:
# YOUR CODE IS HERE 

df.loc[df["EmployeeName"]=="ALBERT PARDINI",["TotalPayBenefits"]]

TotalPayBenefits
2         335279.91

### Who is the lowest paid person?

In [128]:
# YOUR CODE IS HERE 
df.loc[df["TotalPayBenefits"]==df["TotalPayBenefits"].min(),["EmployeeName"]]


EmployeeName
148653    Joe Lopez

### What are the unique Jobs in dataset?

In [129]:
# YOUR CODE IS HERE 

df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 
df.sort_values()


### How many people earned more than avg in 2012?

In [130]:
# YOUR CODE IS HERE 
len(df[df["TotalPayBenefits"] > df["TotalPayBenefits"].mean()][df["Year"] == 2012].index)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


20366

### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________